### ISSUE TITLE
Tests fails due to phantom.js incompatibility

### ISSUE THREAD

**Issue by armish** [hammerlab/pileup.js#165]
When I try to run the tests with `grunt test`, I get this error:

```
$ grunt test

Running "browserify:test" (browserify) task
>> Bundle build/tests.js created.

Running "connect:server" (connect) task
Started connect web server on http://0.0.0.0:9501

Running "mocha_phantomjs:run" (mocha_phantomjs) task

/Users/aksoyb/Projects/pileup.js/node_modules/grunt-mocha-phantomjs/node_modules/phantomjs/lib/location.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              ^

/usr/local/lib/node_modules/phantomjs/lib/location.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              ^
TypeError: Bad argument
    at ChildProcess.spawn (child_process.js:936:24)
    at exports.spawn (child_process.js:736:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Warning: 8 tests failed Use --force to continue.

Aborted due to warnings.
```

More details on the `phantom.js` installed locally:

```
$ npm list phantomjs
pileup@0.1.0 /Users/aksoyb/Projects/pileup.js
└─┬ grunt-mocha-phantomjs@0.6.1
  └── phantomjs@1.9.17 
```

This looks like a problem with a refactored method within phantomjs, but I am not really sure -- what do you think @danvk? Any ideas?

**Comment by danvk** [comment]
Here's what I see:

```
$ npm list phantomjs
pileup@0.1.0 /Users/danvk/github/pileup.js
└─┬ grunt-mocha-phantomjs@0.6.1
  └── phantomjs@1.9.16
```

Maybe it's the `.16`→`.17` change?

**Comment by armish** [comment]
Probably -- I will downgrade my version and give it another try just to make sure.

**Comment by danvk** [comment]
Travis-CI is using Phantom 1.9.17, same as you: https://travis-ci.org/hammerlab/pileup.js#L270

**Comment by armish** [comment]
just updated my node, npm and did a clean install of phantomjs -- the tests now are running without any problems. Looks like it was indeed an installation problem. 

Thanks for double checking this @danvk!

**Comment by danvk** [comment]
Cool, I'm glad that did the trick!
