### ISSUE TITLE
pileup.js doesn't work with node 12.0.0

### ISSUE THREAD

**Issue by piotr-gawron** [hammerlab/pileup.js#517]
I cannot install dependencies when using latest node release:
```
node: v12.0.0
npm: 6.9.0
```

When using node v10.15.3 it's working without problems.

I think the issue is that one of the dependencies relied on node.js internals and in the new version it just broke up. As far as I can tell by the stacktrace the problem is with `natives` library used by old `phantomjs` library.

Here is how it looks in the console:
```
gawi@uni-new:~/workspace/pileup.js$ npm install
npm WARN deprecated istanbul@0.3.22: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated queue-async@1.0.7: renamed to d3-queue
npm WARN deprecated hawk@0.10.2: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated hoek@0.7.6: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@0.3.8: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@0.1.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@0.1.4: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.

> phantomjs@1.9.17 install /home/gawi/workspace/pileup.js/node_modules/phantomjs
> node install.js

fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (/home/gawi/workspace/pileup.js/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/gawi/workspace/pileup.js/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/gawi/workspace/pileup.js/node_modules/phantomjs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
npm WARN prepush-hook@0.1.0 requires a peer of jshint@~2.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by akmorrow13** [comment]
Thanks for bringing this up @piotr-gawron . We need to remove phantomjs and mocha-phantomjs (https://github.com/ariya/phantomjs/issues/14558). I am looking into using [mocha-chrome](https://www.npmjs.com/search?q=mocha-chrome) instead

**Comment by akmorrow13** [comment]
Related to https://github.com/hammerlab/pileup.js/issues/503

**Comment by akmorrow13** [comment]
Fixed with https://github.com/hammerlab/pileup.js/pull/518
